title: Blois Paleoecology Lab
tagline: Quaternary Ecology and Paleoinformatics
baseurl: "/JessicaBloisLab.github.io"
url: "https://erikzepeda59.github.io"
theme: minima
markdown: kramdown
exclude:
- README_project.md
